"""empty message

Revision ID: 3c99475d4e0d
Revises: a84297b413b7
Create Date: 2018-06-12 21:17:02.641731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c99475d4e0d'
down_revision = 'a84297b413b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('front_user', sa.Column('gender', sa.Enum('woman', 'man', 'scret', 'noknow'), nullable=True)
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('front_user', 'gender')
    pass
    # ### end Alembic commands ###
