"""empty message

Revision ID: 60fa02d35f74
Revises: 3c99475d4e0d
Create Date: 2018-06-12 21:21:23.062334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60fa02d35f74'
down_revision = '3c99475d4e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('front_user', sa.Column('gender', sa.Enum('male', 'female', 'secret', 'unknow'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('front_user', 'gender')
    # ### end Alembic commands ###
